# Configura\u00c3\u00a7\u00c3\u00b5es de conex\u00c3\u00a3o com o banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/fintrack?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=Freecs
spring.datasource.password=#SQLUser02
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configura\u00c3\u00a7\u00c3\u00b5es de Seguran\u00c3\u00a7a e JWT
# IMPORTANTE: Em produ\u00c3\u00a7\u00c3\u00a3o, mude esta chave para uma assinatura de tamanho adequado (m\u00c3\u00adnimo de 32 bytes)
# Chave em Base64 para assinatura HMAC-SHA256
api.security.token.secret=MTJjZTM0MmFlYWM1MmRlYTEzNzhjMzc2YzUzZTg4ZjNiYzk3MWEyYzg4ZGYyNDgzODJlYTlhMTM5NWRmOTNjNw==

# Exibir logs detalhados do Spring Security em desenvolvimento (opcional)
logging.level.org.springframework.security=INFO
